/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormularioServicios;
import poo.EmpleadosDal.conexion;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Servicios.Servicios;


/**
 *
 * @author HP
 */
public class FormularioServicios extends javax.swing.JFrame {
   DefaultTableModel modelo;  
    /**
     * Creates new form FormularioServicios
     */
    public FormularioServicios() {
          initComponents();
        String[] titulos={"CodServicio","Nombre"};
        modelo = new DefaultTableModel(null,titulos);
        tblServicios.setModel(modelo);
       mostrarDatos();
       this.Limpiar();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butBuscar = new javax.swing.JButton();
        butRegistrar = new javax.swing.JButton();
        butModificar = new javax.swing.JButton();
        butEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCodServ = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butBuscar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        butBuscar.setForeground(new java.awt.Color(255, 102, 102));
        butBuscar.setText("Buscar");
        butBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuscarActionPerformed(evt);
            }
        });

        butRegistrar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        butRegistrar.setForeground(new java.awt.Color(255, 102, 102));
        butRegistrar.setText("Registrar");
        butRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRegistrarActionPerformed(evt);
            }
        });

        butModificar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        butModificar.setForeground(new java.awt.Color(255, 102, 102));
        butModificar.setText("Modificar");
        butModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butModificarActionPerformed(evt);
            }
        });

        butEliminar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        butEliminar.setForeground(new java.awt.Color(255, 102, 102));
        butEliminar.setText("Eliminar");
        butEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEliminarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Cod_Servicio:");

        txtNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 102, 102));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtCodServ.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtCodServ.setForeground(new java.awt.Color(255, 102, 102));

        tblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServiciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblServicios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butBuscar)
                            .addComponent(butModificar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butRegistrar)
                            .addComponent(butEliminar))
                        .addGap(136, 136, 136))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCodServ, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butBuscar)
                    .addComponent(butRegistrar))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butModificar)
                    .addComponent(butEliminar))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butBuscarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
    
    }//GEN-LAST:event_txtNombreActionPerformed

    private void butRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRegistrarActionPerformed
   conexion objconexion = new conexion();
    Servicios oServicios=recuperarDatos();
    String srtSentenciaInsert=String.format("INSERT INTO Servicios (CodServicio, Nombre) "
            + " VALUES (null,'%s')",oServicios.getNombre());
   objconexion.ejecutarSentenciaSQL(srtSentenciaInsert);
    try {
        ResultSet resultado=objconexion.ConsultarRegistros("SELECT * FROM Servicios");
        
        while(resultado.next())
        {
            System.out.println(resultado.getString("CodServicio"));
            System.out.println(resultado.getString("Nombre"));
        }
    }catch (Exception e){
     System.out.println(e);
    }
    this.mostrarDatos();
    this.Limpiar();
    }//GEN-LAST:event_butRegistrarActionPerformed

    private void butModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butModificarActionPerformed
    conexion objConexion=new conexion();
    
    Servicios oServicios=recuperarDatos();
    String strSentenciaInsert= String.format("UPDATE Servicios SET Nombre = '%s',"
            + " WHERE CodServicio=%d",oServicios.getNombre(),oServicios.getCodServicio());
    objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
    this.mostrarDatos();
    this.Limpiar();
    }//GEN-LAST:event_butModificarActionPerformed

    private void butEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEliminarActionPerformed
  conexion objConexion=new conexion();
    
    Servicios oServicios=recuperarDatos();
    String strSentenciaInsert= String.format(" DELETE FROM Servicios WHERE CodServicio=%d",oServicios.getCodServicio());
    objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
    this.mostrarDatos();
    this.Limpiar();
    }//GEN-LAST:event_butEliminarActionPerformed

    private void tblServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiciosMouseClicked
        if(evt.getClickCount()==1){
            
            
        JTable Receptor =(JTable)evt.getSource();
        txtCodServ.setText(Receptor.getModel().getValueAt(Receptor.getSelectedRow(),0).toString());
        txtNombre.setText(Receptor.getModel().getValueAt(Receptor.getSelectedRow(),1).toString());      
        butRegistrar.setEnabled(false);
        butModificar.setEnabled(true);
        butEliminar.setEnabled(true);
        
        }    
        
    }//GEN-LAST:event_tblServiciosMouseClicked
     public void mostrarDatos(){
         while(modelo.getRowCount() >0 ){
            modelo.removeRow(0);
        }
         conexion objconexion = new conexion();
         try {
        ResultSet resultado=objconexion.ConsultarRegistros("SELECT * FROM Servicios");
        
        while(resultado.next())
        {
            System.out.println(resultado.getString("CodServicio"));
            System.out.println(resultado.getString("Nombre"));
            
            Object[] usuario={resultado.getString("CodServicio"),resultado.getString("Nombre")};
            modelo.addRow(usuario);
        }
    }catch (Exception e){
     System.out.println(e);
    }
         }
     
    
    public Servicios recuperarDatos(){
        Servicios oServicios=new  Servicios();
        int CodServicio=(txtCodServ.getText().isEmpty())?0:Integer.parseInt(txtCodServ.getText());
        oServicios.setCodServicio(CodServicio);
        oServicios.setNombre(txtNombre.getText());

        return oServicios;
}
     
     public void Limpiar (){
        txtCodServ.setText("");
        txtNombre.setText("");
      
        butRegistrar.setEnabled(true);
        butModificar.setEnabled(false);
        butEliminar.setEnabled(false);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioServicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBuscar;
    private javax.swing.JButton butEliminar;
    private javax.swing.JButton butModificar;
    private javax.swing.JButton butRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblServicios;
    private javax.swing.JTextField txtCodServ;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
